const companies = {
  1: {
    id: 1,
    name: "19",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "19 is a coding platform based on peer-to-peer learning, open 24/7, for all 18+, totally free for its participants thanks to the financing of sponsors, and being part of the 42 Network",
    followers: 250,
  },
  2: {
    id: 2,
    name: "Alter Educs",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Improving the quality of life of kids in Belgium's public schools",
    followers: 250,
  },
  3: {
    id: 3,
    name: "Be education",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Helping educational companies and NGOs to improve Belgium's public education system",
    followers: 250,
  },
  4: {
    id: 4,
    name: "BeCode",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Free 7-month trainings in Web Development, AI, DevOps or CyberSecurity. No diploma needed.",
    followers: 250,
  },
  5: {
    id: 5,
    name: "Bibliothèque sans frontières",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Bibliothèques Sans Frontières wants to bring knowledge and information to those who are most in need.",
    followers: 250,
  },
  6: {
    id: 6,
    name: "Bruxelles formation",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Bruxelles Formation is the French-speaking public service in charge of professional training in the Brussels Region.",
    followers: 250,
  },
  7: {
    id: 7,
    name: "Cosearching Brussels",
    picture: "/src/content/backbecode.png",
    logo: "/src/content/becode.png",
    description:
      "Co-searching.brussels, a place solely dedicated to knowledge and experience sharing between jobseekers.",
    followers: 250,
  },

  // "CodeNplay",
  // "Cool@School",
  // "CWF",
  // "eqla",
  // "EducIT",
  // "Google digitaal atelier",
  // "Hack your future",
  // "Khan Academy",
  // "Le wagon",
  // "mediawijs",
  // "Orange Digital Center",
  // "skills factory",
  // "Solvay",
  // "Switchfully",
  // "Teach for belgium",
  // "Techies lab",
  // "Agence Digitale Solidaire",
  // "alan",
  // "AR#S",
  // "beAngels",
  // "bundl",
  // "campfire",
  // "clyde.and.bonnie",
  // "Curewiki",
  // "d-teach",
  // "D4D HUB",
  // "DataPrep",
  // "FARI",
  // "flowchase",
  // "Free Ukraine",
  // "hub brussels",
  // "inflights",
  // "M44",
  // "Mojo",
  // "moon9",
  // "nextmo-ov",
  // "nextORIGIN",
  // "NOSKUA",
  // "Outsight Studio",
  // "redpencil.io",
  // "RingTwice",
  // "Rosa",
  // "SCALEFUND",
  // "Simple Backups",
  // "skipr",
  // "SocialCom",
  // "sortlist",
  // "startup factory",
  // "Stooml-nk.",
  // "sustAIn.brussels",
  // "tech eu",
  // "TYREL",
  // "UNBLND",
  // "Valkuren",
  // "zerocopy",
  // "ALLIED FOR STARTUPS",
  // "The Democratic Society",
  // "Ecas",
  // "ESN",
  // "King Baudouin Foundation",
  // "open knowledge belgium",
  // "We tech care",
};
export default companies;
