const companies={
    1: {
        id: 1,
        name: "19",
        picture: "https://storage.gra.cloud.ovh.net/v1/AUTH_f15a805d8d064e3d888db44fc6b34d2f/becentral/files/fF8x8DjXFHNcr8NhTsGXCIz7hsfGxfw3fEz6QoFu.svg",
        description: "19 is a coding platform based on peer-to-peer learning, open 24/7, for all 18+, totally free for its participants thanks to the financing of sponsors, and being part of the 42 Network",
        followers: 250,
      },
      2: {
        id: 2,
        name: "Alter Educs",
        picture: "/src/content/profile1.png",
        description: "",
        followers: 250,
      },
    "Be education",
    "BeCode",
    "Bibliothèque sans frontières",
    "Bruxelles formation",
    "Cosearching Brussels",
    "CodeNplay",
    "Cool@School",
    "CWF",
    "eqla",
    "EducIT",
    "Google digitaal atelier",
    "Hack your future",
    "Khan Academy",
    "Le wagon",
    "mediawijs",
    "Orange Digital Center",
    "skills factory",
    "Solvay",
    "Switchfully",
    "Teach for belgium",
    "Techies lab",
    "Agence Digitale Solidaire",
    "alan",
    "AR#S",
    "beAngels",
    "bundl",
    "campfire",
    "clyde.and.bonnie",
    "Curewiki",
    "d-teach",
    "D4D HUB",
    "DataPrep",
    "FARI",
    "flowchase",
    "Free Ukraine",
    "hub brussels",
    "inflights",
    "M44",
    "Mojo",
    "moon9",
    "nextmo-ov",
    "nextORIGIN",
    "NOSKUA",
    "Outsight Studio",
    "redpencil.io",
    "RingTwice",
    "Rosa",
    "SCALEFUND",
    "Simple Backups",
    "skipr",
    "SocialCom",
    "sortlist",
    "startup factory",
    "Stooml-nk.",
    "sustAIn.brussels",
    "tech eu",
    "TYREL",
    "UNBLND",
    "Valkuren",
    "zerocopy",
    "ALLIED FOR STARTUPS",
    "The Democratic Society",
    "Ecas",
    "ESN",
    "King Baudouin Foundation",
    "open knowledge belgium",
    "We tech care",
}